/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module binaryToBCD_11 (
    input [7:0] binary,
    output reg [3:0] digit0,
    output reg [3:0] digit1,
    output reg [3:0] digit2
  );
  
  
  
  integer i;
  
  reg [7:0] binaryInput;
  
  reg [3:0] hundreds;
  
  reg [3:0] tens;
  
  reg [3:0] ones;
  
  always @* begin
    binaryInput = binary;
    hundreds = 4'h0;
    tens = 4'h0;
    ones = 4'h0;
    for (i = 1'h0; i <= 3'h7; i = i + 1) begin
      if (hundreds >= 4'h5) begin
        hundreds = hundreds + 2'h3;
      end
      if (tens >= 4'h5) begin
        tens = tens + 2'h3;
      end
      if (ones >= 4'h5) begin
        ones = ones + 2'h3;
      end
      hundreds = hundreds << 1'h1;
      hundreds[0+0-:1] = tens[3+0-:1];
      tens = tens << 1'h1;
      tens[0+0-:1] = ones[3+0-:1];
      ones = ones << 1'h1;
      ones[0+0-:1] = binaryInput[7+0-:1];
      binaryInput = binaryInput << 1'h1;
    end
    digit2 = hundreds;
    digit1 = tens;
    digit0 = ones;
  end
endmodule
