/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifterUnit_5 (
    input [5:0] alufn,
    input [7:0] a,
    input [2:0] b,
    output reg [7:0] shifted
  );
  
  
  
  reg [8:0] temp;
  
  always @* begin
    
    case (alufn[0+3-:4])
      4'h0: begin
        temp = a << b[0+2-:3];
      end
      4'h1: begin
        temp = a >> b[0+2-:3];
      end
      4'h2: begin
        temp = $signed(a) <<< b[0+2-:3];
      end
      4'h3: begin
        temp = $signed(a) >>> b[0+2-:3];
      end
      default: begin
        temp = 9'h000;
      end
    endcase
    shifted = temp[0+7-:8];
  end
endmodule
