/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module logic_3 (
    input clk,
    input rst,
    input [23:0] io_dip,
    output reg outS,
    output reg outC
  );
  
  
  
  
  reg a;
  
  reg b;
  
  reg cin;
  
  always @* begin
    a = io_dip[16+0+0-:1];
    b = io_dip[8+0+0-:1];
    cin = io_dip[0+0+0-:1];
    outS = (a ^ b) ^ cin;
    outC = ((a ^ b) * cin) + a * b;
  end
endmodule
