/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     DIGITS = 4
     DIV = 16
*/
module multi_LED_digit_6 (
    input clk,
    input rst,
    input expectedC,
    input expectedS,
    input outC,
    input outS,
    output reg [6:0] seg,
    output reg [3:0] sel,
    output reg [7:0] matching_led
  );
  
  localparam DIGITS = 3'h4;
  localparam DIV = 5'h10;
  
  
  localparam DIGIT_BITS = 2'h2;
  
  wire [2-1:0] M_ctr_value;
  counter_14 ctr (
    .clk(clk),
    .rst(rst),
    .value(M_ctr_value)
  );
  
  wire [7-1:0] M_led_dec_segs;
  reg [4-1:0] M_led_dec_char;
  led_digit_15 led_dec (
    .char(M_led_dec_char),
    .segs(M_led_dec_segs)
  );
  
  wire [4-1:0] M_digit_dec_out;
  reg [2-1:0] M_digit_dec_in;
  decoder_16 digit_dec (
    .in(M_digit_dec_in),
    .out(M_digit_dec_out)
  );
  
  always @* begin
    
    case (M_ctr_value)
      1'h0: begin
        M_led_dec_char = expectedC;
      end
      1'h1: begin
        M_led_dec_char = outC;
      end
      2'h2: begin
        M_led_dec_char = expectedS;
      end
      2'h3: begin
        M_led_dec_char = outS;
      end
      default: begin
        M_led_dec_char = 4'h9;
      end
    endcase
    seg = M_led_dec_segs;
    M_digit_dec_in = M_ctr_value;
    sel = M_digit_dec_out;
    if (outC == expectedC && outS == expectedS) begin
      matching_led = 8'hff;
    end else begin
      matching_led = 8'h00;
    end
  end
endmodule
