/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module logic_7 (
    input clk,
    input rst,
    input [23:0] io_dip,
    output reg expectedS,
    output reg expectedC
  );
  
  
  
  
  reg a;
  
  reg b;
  
  reg cin;
  
  always @* begin
    a = io_dip[0+7+0-:1];
    b = io_dip[0+6+0-:1];
    cin = io_dip[0+5+0-:1];
    expectedS = (a ^ b) ^ cin;
    expectedC = ((a ^ b) * cin) + a * b;
  end
endmodule
