/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [7-1:0] M_multi_led_seg;
  wire [4-1:0] M_multi_led_sel;
  reg [1-1:0] M_multi_led_outC;
  reg [1-1:0] M_multi_led_outS;
  multi_LED_digit_2 multi_led (
    .clk(clk),
    .rst(rst),
    .outC(M_multi_led_outC),
    .outS(M_multi_led_outS),
    .seg(M_multi_led_seg),
    .sel(M_multi_led_sel)
  );
  wire [1-1:0] M_logic_outS;
  wire [1-1:0] M_logic_outC;
  reg [24-1:0] M_logic_io_dip;
  logic_3 logic (
    .clk(clk),
    .rst(rst),
    .io_dip(M_logic_io_dip),
    .outS(M_logic_outS),
    .outC(M_logic_outC)
  );
  wire [1-1:0] M_ctr_value;
  counter_4 ctr (
    .clk(clk),
    .rst(rst),
    .value(M_ctr_value)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    M_logic_io_dip = io_dip;
    M_multi_led_outC = M_logic_outC;
    M_multi_led_outS = M_logic_outS;
    io_seg = ~M_multi_led_seg;
    io_sel = ~M_multi_led_sel;
    io_led = io_dip;
  end
endmodule
