/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adderUnit_4 (
    input [5:0] alufn,
    input [7:0] a,
    input [7:0] b,
    output reg [7:0] added,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [8:0] val;
  
  always @* begin
    
    case (alufn[0+3-:4])
      4'h0: begin
        val = a + b;
      end
      4'h1: begin
        val = a - b;
      end
      4'h2: begin
        val = a * b;
      end
      4'h3: begin
        val = a / b;
      end
      4'h4: begin
        val = a / b * a;
      end
      4'h5: begin
        val = ~a;
      end
      default: begin
        val = 9'h000;
      end
    endcase
    added = val[0+7-:8];
    z = (|val);
    v = a[7+0-:1] * b[7+0-:1] * ~val[7+0-:1] + ~a[7+0-:1] * ~b[7+0-:1] * val[7+0-:1];
    n = a[7+0-:1] - b[7+0-:1];
  end
endmodule
