/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module booleanUnit_6 (
    input [5:0] alufn,
    input [7:0] a,
    input [7:0] b,
    output reg [7:0] booleaned
  );
  
  
  
  reg [8:0] temp;
  
  always @* begin
    
    case (alufn[1+3-:4])
      4'hc: begin
        temp = a & b;
      end
      4'hf: begin
        temp = a | b;
      end
      4'hb: begin
        temp = a ^ b;
      end
      4'hd: begin
        temp = a;
      end
      default: begin
        temp = 9'h000;
      end
    endcase
    booleaned = temp[0+7-:8];
  end
endmodule
