/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module comparatorUnit_7 (
    input [5:0] alufn,
    input z,
    input v,
    input n,
    output reg compared
  );
  
  
  
  reg out;
  
  always @* begin
    
    case (alufn[0+3-:4])
      4'h3: begin
        out = z;
      end
      4'h5: begin
        out = n ^ v;
      end
      4'h7: begin
        out = z + (n ^ v);
      end
      default: begin
        out = $signed(2'h3);
      end
    endcase
    compared = out;
  end
endmodule
