/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    output reg spi_miso,
    output reg [3:0] spi_channel,
    output reg avr_rx,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  reg [7:0] a;
  
  reg [7:0] b;
  
  reg [5:0] alufn;
  
  wire [8-1:0] M_alu_result;
  reg [6-1:0] M_alu_alufn;
  reg [8-1:0] M_alu_a;
  reg [8-1:0] M_alu_b;
  aluUnit_1 alu (
    .clk(clk),
    .alufn(M_alu_alufn),
    .a(M_alu_a),
    .b(M_alu_b),
    .result(M_alu_result)
  );
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_2 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [7-1:0] M_multi_led_seg;
  wire [4-1:0] M_multi_led_sel;
  reg [8-1:0] M_multi_led_a;
  reg [8-1:0] M_multi_led_b;
  reg [8-1:0] M_multi_led_value;
  reg [5-1:0] M_multi_led_button;
  multi_LED_digit_3 multi_led (
    .clk(clk),
    .rst(rst),
    .a(M_multi_led_a),
    .b(M_multi_led_b),
    .value(M_multi_led_value),
    .button(M_multi_led_button),
    .seg(M_multi_led_seg),
    .sel(M_multi_led_sel)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = 8'h00;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    io_led = 24'h000000;
    io_seg = 8'hff;
    io_sel = 4'hf;
    a = io_dip[16+7-:8];
    b = io_dip[8+7-:8];
    alufn = io_dip[0+2+5-:6];
    M_alu_a = a;
    M_alu_b = b;
    M_alu_alufn = alufn;
    M_multi_led_a = a;
    M_multi_led_b = b;
    M_multi_led_value = M_alu_result;
    M_multi_led_button = io_button;
    io_led = io_dip;
    io_seg = ~M_multi_led_seg;
    io_sel = ~M_multi_led_sel;
    io_led[0+0+1-:2] = 1'h0;
  end
endmodule
